// ...existing code...
try {
    // ...existing code where the connection is being established...
} catch (error) {
    console.error('Error establishing connection:', error);
    throw error;
}
// ...existing code...
